### ISSUE TITLE
Update SUMMARY.md

### ISSUE THREAD

**Issue by RaoOfPhysics** [edovio/OpenStudentBook#13]
See https://toolchain.gitbook.com/pages.html

The current GitBook doesn't have all the chapters. Would be good to include them while building! :)

**Comment by edovio** [comment]
I think to to fix this issue with the last commit

**Comment by edovio** [comment]
Now the GitBook are connected. please @RaoOfPhysics see if all for you works! :)

**Comment by RaoOfPhysics** [comment]
Glad that the GitBook is connected! I guess the next thing to do would be to split the the Italian and English chapters: see https://toolchain.gitbook.com/languages.html

**Comment by edovio** [comment]
Thanks @RaoOfPhysics!!!

**Comment by edovio** [comment]
@RaoOfPhysics I performed the Multilanguages option in GitBook. We need to finish to make the localization in English and to finish to edit the text in Italian.
