### ISSUE TITLE
Open License

### ISSUE THREAD

**Issue by abbycabs** [edovio/OpenStudentBook#30]
We'd like to promote the use of open licenses in our Open Project programs. CC-BY-NC isn't considered an open license / free culture work.

Read more here:
https://creativecommons.org/share-your-work/public-domain/freeworks/

May I suggest CC-BY or CC-BY-SA?

**Comment by edovio** [comment]
yeah sure! It's OK for me !!! :) I Change it now!

**Comment by edovio** [comment]
Changed the License!!!
